### ISSUE TITLE
UnicodeEncodeError: 'charmap' codec can't encode character

### ISSUE THREAD

**Issue by realkibou** [JoeBashe/stl-scraper#1]
Was using stl.py search "Hannover, Germany"

it was running and giving me warnings about Duplicate Listings, which is fine I guess. But then it broke with the following error:

Traceback (most recent call last):
  File "C:\_Code\AirbnbCrawler\stl-scraper-main\stl.py", line 21, in <module>
    main()
  File "C:\_Code\AirbnbCrawler\stl-scraper-main\stl.py", line 17, in main
    StlCommand().execute(arguments)
  File "C:\_Code\AirbnbCrawler\stl-scraper-main\stl\command\stl_command.py", line 60, in execute
    scraper.run(query, params)
  File "C:\_Code\AirbnbCrawler\stl-scraper-main\stl\scraper\airbnb_scraper.py", line 61, in run
    self.__persistence.save(query, listings)
  File "C:\_Code\AirbnbCrawler\stl-scraper-main\stl\persistence\csv.py", line 15, in save
    writer.writerows(listings)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\lib\csv.py", line 157, in writerows
    return self.writer.writerows(map(self._dict_to_list, rowdicts))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f603' in position 19374: character maps to <undefined>

**Comment by JoeBashe** [comment]
Hi @realkibou thanks for the question!

> it was running and giving me warnings about Duplicate Listings

Yes, that is a result of the same listing being returned by Airbnb when paging through listings. It can be safely ignored.

> But then it broke with the following error:
>  UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f603' in position 19374: character maps to 

Ahh fun unicode errors. :smile:  It looks like the error is happening during CSV creation. I haven't tested the script on windows so I haven't run into that error. 

>  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\lib\encodings\**cp1252.py**", line 19, in encode

The encoding **cp1252** is a Windows encoding, but I think python is expecting UTF-8. Some [quick googling](https://stackoverflow.com/questions/12752313/unicodedecodeerror-in-python-3-when-importing-a-csv-file) shows there may be a `PYTHONIOENCODING` env var you can set. Please let me know what solution you find and I can update the repo / merge a PR if necessary.

**Comment by realkibou** [comment]
Change .\persistence\csv.py line 12 to:
with open(self.__csv_path, 'w', **encoding='utf-8'**) as csvfile:

**Comment by JoeBashe** [comment]
Great! Thank you. Just pushed a commit to add that: https://github.com/JoeBashe/stl-scraper/commit/5fbaab12312f402f3b7f0ca7239293045539a6b2
